name: Jekyll site CI

on:
  push:
    branches: [ "source" ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - name: 📂 setup
      uses: actions/checkout@v3
      
    - name: 💎 setup ruby
      uses: ruby/setup-ruby@v1.110.0
      with:
        ruby-version: 2.7

    - name: 🔨 install dependencies & build site
      uses: limjh16/jekyll-action-ts@v2
      with:
        enable_cache: true
        
    - name: 🚀 deploy
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
#         publish_branch: master
